### ISSUE TITLE
Reference color styles in tooltips

### ISSUE THREAD

**Issue by bradryanbice** [ph1p/figma-measure#20]
It would be really great to reference the color style name (or have the option to do so) in the tooltips instead of the hex code. 

My use case is I am diagraming some components for reference and I want my developers to reference the color style name (variable) instead of the hex (or alongside it, similar to the inspector view). It's also good reference for designers so that they will learn and adapt to using color styles in stead of hex codes.

**Comment by ph1p** [comment]
Thank you! That is quite very useful I will see how I can best incorporate it into the new version.

**Comment by ph1p** [comment]
I've implemented it in the new version (:

**Comment by bradryanbice** [comment]
Wow, this is great. Thank you!
