### ISSUE TITLE
Percentage opacity gives too many decimal places

### ISSUE THREAD

**Issue by bradryanbice** [ph1p/figma-measure#21]
Seemingly any Layer opacity value other than `25`, `50`, `75`, or `100` will display a percentage with a lot of decimal places, such as shown in the screen shot.

<img width="210" alt="CleanShot 2021-05-13 at 08 35 49@2x" src="https://user-images.githubusercontent.com/8323556/118126730-b9617300-b3c6-11eb-92fa-e2280abbc84d.png">

**Comment by ph1p** [comment]
Thank you! I'll fix it as soon as I can (:

**Comment by ph1p** [comment]
Fixed with new version.
