### ISSUE TITLE
Auto-layout Support

### ISSUE THREAD

**Issue by kctdfh** [ph1p/figma-measure#24]
Hey! Thanks for the amazing plugin - we use it a lot and it has simplified communications greatly! 

We use a lot of auto-layout and the plugin currently can't show a line for the distance between an element and its parent since you can't select them both at the same time. So I was thinking that it'd be great to have a new area for measuring an auto-layout spacing value.

You'd choose the parent that has the auto-layout and then get the ability to add a redline for the distance between the parent and its child (i.e. auto-layout padding amount)

Here's a mock-up of what I'm thinking:

![figmaMeasure-AutoLayout](https://user-images.githubusercontent.com/28873487/122470476-1931d780-cf8c-11eb-8326-8127aced3549.png)

Thanks again

**Comment by ph1p** [comment]
Hi @kctdfh good to hear! (:
Thank you for the great suggestion. I'm currently a little bit busy,  but I am already at something like this on this branch https://github.com/ph1p/figma-measure/tree/version2.2.

**Comment by ph1p** [comment]
Closed with new version.
