### ISSUE TITLE
Ability to change font size?

### ISSUE THREAD

**Issue by hfahmy** [ph1p/figma-measure#27]
Is it possible to change font size? If not will this be added as a feature?

**Comment by ph1p** [comment]
Hi @hfahmy!
I will have a look at how I can implement it best

**Comment by yinrenzhangsir** [comment]
这对我非常有用，如果做一些精细的标注，比如12px甚至更小时，很多标注会相互覆盖，希望可以增加一个缩小的设置把标注信息缩小，现在运用到工作中还是有很多困难，比如我想做到这样就几乎不可能
![CleanShot 2021-09-27 at 10 28 18](https://user-images.githubusercontent.com/39354019/134836994-353234a3-c4c0-47a5-9f59-4d38bd290148.png)

**Comment by eightbit** [comment]
Extremely useful plugin - thanks so much!
+1 for larger fonts

**Comment by ph1p** [comment]
Thanks @eightbit ! I'm currently working on this feature (https://github.com/ph1p/figma-measure/tree/feature/settings) and some
more useful stuff. It should be ready next week (:

**Comment by eightbit** [comment]
Thank you!
