### ISSUE TITLE
Label Tooltip

### ISSUE THREAD

**Issue by dcarmona05** [ph1p/figma-measure#3]
Would be awesome to have a simple (pointing hovercard) to insert spec layer details, with a slight elevation style.

**Comment by ph1p** [comment]
Hi! I don't quite know what you mean. Can you please give me a small example (maybe a screenshot or something)?
Thanks ;)

**Comment by dcarmona05** [comment]
<img width="881" alt="Screen Shot 2019-11-22 at 1 04 01 PM" src="https://user-images.githubusercontent.com/12519916/69460321-b41eed00-0d28-11ea-846e-b89879e4c95c.png">

"Sketch Measure" plugin was a huge asset/resource and many features would really help the spec'ing process :D Thanks way in advance if this idea was already suggested

**Comment by ph1p** [comment]
Oh this is cool! I try to implement it as soon as I can (:

**Comment by ph1p** [comment]
Hi @dcarmona05! I've finally published a new version. Hope you like it! I will try ship updates more often and add checkboxes to customize the tooltip content.

**Comment by dcarmona05** [comment]
This is amazing will test out today and see how the team feels
