### ISSUE TITLE
Request/Issue - Don't lock child layers

### ISSUE THREAD

**Issue by megaroeny** [ph1p/figma-measure#30]
## Problem
The issue with how you have it now, where some child layers/groups are locked, is if designers are moving objects around and want to include the spec measurements with those moves. I have to dig through all the layer groups and unlock them.

## Improvements

1. Simply just don't lock any child layers or groups in the "📐 Measurements" group you generate.
2. Update the "refresh" button so it recognizes all measured objects new positions

### Related enhancement
If refreshed, keep the different colors the user has set. For example, I like to use different colors for padding, spacing, and sizing:
![image](https://user-images.githubusercontent.com/1559447/148864877-38f6698e-66c7-4c67-b273-24e07bd0c38a.png)

**Comment by ph1p** [comment]
Hi @megaroeny thank you for reaching out! I'm currently working on a new version, where I try to make the whole layer handling better (including your suggestion :) ).

Likewise, updating the elements is part of it. Unfortunately, Figma can sometimes be the bottleneck here with too large files. I try to keep the plugin as performant as possible and avoid unnecessary iterations over elements. This is for example also the reason why there is a global group. I am also trying to improve this in the upcoming version.

**Comment by megaroeny** [comment]
@ph1p cool sounds great! And no worries. Happy to hear it and good luck!
