### ISSUE TITLE
Request: Lock new Measurements group?

### ISSUE THREAD

**Issue by megaroeny** [ph1p/figma-measure#31]
I LOVE the new update, and that the global group is gone. With that said, can you lock the new group that is being generated again? It gets in the way of making more measurements. I think this use case will be more common, than folks wanting to edit/move the layers inside the _Measurements_ group. Thanks!

**Comment by ph1p** [comment]
Thank you :) and good to hear! I thought the locking feature would interfere. Maybe we can find a cool way via an additional settings page, because changing font sizes is still on my list as well. I keep you up to date!

**Comment by megaroeny** [comment]
> Thank you :) and good to hear! I thought the locking feature would interfere. Maybe we can find a cool way via an additional settings page, because changing font sizes is still on my list as well. I keep you up to date!

Yeah that would be cool, if you have the time of course. Settings are always a nice to have. And of course this if from my own observation, curious what others workflow is like.

**Comment by ph1p** [comment]
@megaroeny With the latest update you can now lock both groups separately
