### ISSUE TITLE
Bug: Padding

### ISSUE THREAD

**Issue by gupta-vidit** [ph1p/figma-measure#32]
While marking up the padding for a component (that is built using auto-layout), the red lines that are produced are wrong. Please find the attached video as a reference.

https://user-images.githubusercontent.com/39264121/155132487-c4cd3609-6951-4dd9-847d-5c0a5d321735.mov

**Comment by ph1p** [comment]
Thanks for reporting! Could you please invite me to your file or a small reproduction of this bug? (me@ph1p.dev)

**Comment by popenke** [comment]
I had a similar issue yesterday and it seemed to me that Measure was trying to include the size of the shadow effect into the calculation. 

**Removing the shadows kinda solves the problem, then you can add the shadow back again.**

**Comment by ph1p** [comment]
@popenke yeah I'm aware of that :/ Maybe I will find a way to calculate the correct size. 
This is similar to exporting a selected element with shadow. Sometimes it's intended, but sometimes you first have to remove the shadow to export it "correctly".

**Comment by popenke** [comment]
Perhaps a checkbox to choose whether Measure should/shouldn't include shadows in the calculation could solve this if there's a way to ignore the shadows.

**Comment by ph1p** [comment]
@popenke I implemented a first fix today. Drop shadows are now detected and taken into account in the padding calculation.
