### ISSUE TITLE
Padding on Objects with Auto layout

### ISSUE THREAD

**Issue by MaikRieff** [ph1p/figma-measure#45]
Hey Phil, I already mentioned this on Figma. 

When I try to use the measure tool for padding values on objects that have auto layout applied to them, it just doesn't work. 
You can see at the end of the clip I tried the tool on an object that doesn't has Auto layout applied and the padding values show up. So it seems like the problem is caused by the Auto layout and not it being a component. 

Thank you for your help and improvements on this tool. If you need anything else from me, message me.

https://user-images.githubusercontent.com/115167787/194342548-3507ded4-c7f2-4d27-b1e1-33899987c20e.mp4

Best, 

Maik R

**Comment by ph1p** [comment]
Thank you! Is it possible for you to invite me to your file or to a copy of it? (me@ph1p.dev)

**Comment by MaikRieff** [comment]
I invited you to the file. If you didn't get an invite, here is the link. https://www.figma.com/file/Uy8alD4CLD6WnbBYZGnlSH/Auto-Layout-Test-File?node-id=0%3A1
Just ask for access permission, and I'll take care of the role you are assigned to.

**Comment by ph1p** [comment]
Hi @MaikRieff! I took a closer look at the whole thing and found the error. Frames count as an additional auto-layout element, so I excluded them. Now I looked for the closest parent element and moved the measurements to the closest measurement group, which must not be in an auto layout. 

I have created a version that you can test. Just unzip it and import it. Plugins > Development > Import plugin from manifest... > open the manifest.json. Now you can find it in the plugin development menu.

[Measure.zip](https://github.com/ph1p/figma-measure/files/9731810/Measure.zip)

**Comment by MaikRieff** [comment]
Sorry to bother you again Philip. It is working now when using auto layout! Amazing job!
Unfortunately it doesn't work when the objects you want to measure are components that have auto layout applied to them.

**Comment by MaikRieff** [comment]
Uploading test.mp4…

Am I doing something wrong ? Thank you for the quick work!

**Comment by MaikRieff** [comment]
Am I doing something wrong? Thanks for the quick turn around! 

https://user-images.githubusercontent.com/115167787/194652252-698d5fea-0416-4767-b12a-9b22fe3be9fc.mp4

**Comment by ph1p** [comment]
I think now its fixed. Please try it again. I've updated the recursive group search, because I cannot create nodes inside instances.

**Comment by MaikRieff** [comment]
Hey Philip, thank you for all the quick and hard work. It is working now. You are the best!

**Comment by MaikRieff** [comment]
Hey ph1p, is there a way to apply the measurements for padding inside of components without having to adjust their placement? In my current situation when measuring button padding, the measurement will overlay over the measuring line. Do you think there is a solution for that?

When I apply the measurement it looks like this:
<img width="345" alt="Screen Shot 2022-10-20 at 3 27 50 PM" src="https://user-images.githubusercontent.com/115167787/197040103-0af6c1a6-dab5-4e47-b6ea-fdb71149065a.png">

Instead it would be great if there is some kind of tool that lets me designate how much space is between the measurement and the measurement line. 
So it could look something like this:
<img width="374" alt="Screen Shot 2022-10-20 at 3 29 13 PM" src="https://user-images.githubusercontent.com/115167787/197040348-6091fffe-b276-413a-b10b-1daece72d1cc.png">

Also let me know your Venmo or Paypal so my manager and I can invite you to a coffee!

**Comment by ph1p** [comment]
Hi, I'll take a look at it! It's definitely possible to do that.

I should also rethink the UI a bit, because there are many things and I don't want to create too much clutter 😅.

This is really nice, you do not have to, but if you want, my paypal is @ph1p

**Comment by MaikRieff** [comment]
Haha no problem, you deserve it. I sent you a little treat, I forgot to attach a note. 😃
