### ISSUE TITLE
How to remove the measure

### ISSUE THREAD

**Issue by Flavien8396** [ph1p/figma-measure#7]
Hello,

Thanks for the work done ! But I didn't find where I can hide the measure on an object.
Thanks for your help.

Flavien

![image](https://user-images.githubusercontent.com/66060567/83118643-e8f07000-a0ce-11ea-8ac4-2dff2e89a856.png)

**Comment by ph1p** [comment]
Hi @Flavien8396, currently this is not possible, but I will add it as soon as I can ;)

**Comment by ph1p** [comment]
At the moment all measurements are moved into a separate group. There you can change the visibility.

**Comment by Flavien8396** [comment]
Hello Phil
Thanks for the reply, I didn't see that the measures were in a separate group ;-)

**Comment by ph1p** [comment]
Oh ok. I'll take a look at it as soon as I can (: and publish a new version. I'll keep you posted.

**Comment by ph1p** [comment]
This feature is included in the new release (:
