### ISSUE TITLE
Ability to measure space

### ISSUE THREAD

**Issue by joshdiaz-me** [ph1p/figma-measure#8]
thanks for building this plugin (and for fixing the issue with the install prompt showing up on every node!)

are there any plans to add the ability to measure spacing? it would be awesome to be able to measure the space between objects that are next to each other as well as the space between objects that are on top of each other.

**Comment by ph1p** [comment]
hi, glad you like it :) I also like this feature and have thought about it. I will also fix the bug directly. Unfortunately I can only start with it at the beginning of next week. I will contact you as soon as I have everything ready.

**Comment by rodmehs** [comment]
I'm also interested in this functionality.

**Comment by ph1p** [comment]
Sorry for the delay :/ in the next days I will really look at it, since I want to refactor the plugin for quite a while anyway (:

**Comment by rodmehs** [comment]
@ph1p That's great to hear. Thank you for taking the time to work on this!

**Comment by ph1p** [comment]
@rodmehs, @joshdiaz-me little info to keep you up to date. I have finished all the calculations, now I am tidying everything up a bit and adding it to the plugin. Here is my progress: https://9y6y5.csb.app/

**Comment by ph1p** [comment]
First version released :)
